import Head from 'next/head'
import StepperCounterBar from '../components/stepper/StepperCounterBar'
import StepperBackNextControl from '../components/stepper/StepperBackNextControl'
import Account from '../components/stepper/storeOwnerRegisterSteps/Account'
import Details from '../components/stepper/storeOwnerRegisterSteps/Details'
import Final from '../components/stepper/storeOwnerRegisterSteps/Final'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {

  const [currentStep, setCurrentStep] = useState(1)
  const steps = [
    "Account Information",
    "Personal Details",
    "Complete"
  ]

  const displayStep = (step) => {
    switch (step) {
      case 1:
        return <Account />
      case 2:
        return <Details />
      case 3:
        return <Final />
    }
  }

  const handleClick = (direction) => {
    let newStep = currentStep
    direction == "next" ? newStep++ : newStep--
    newStep > 0 && newStep <= steps.length && setCurrentStep(newStep)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:w-1/2 mx-auto shadow-xl rounded-2xl pb-2 bg-white">

        {/* Stepper */}
        <div className="container horizontal mt-5">
          <StepperCounterBar
            steps={steps}
            currentStep={currentStep}
          />
          {/* Display Components */}
        </div>

        {/* Navigation controls */}
        <div className="my-10 p-10">
          {displayStep(currentStep)}
        </div>
        {currentStep != steps.length &&
          <StepperBackNextControl
            handleClick={handleClick}
            currentStep={currentStep}
            steps={steps}
          />
        }
      </main>
    </div>
  )
}
